apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: u7c4c11lw-python
  janus-idp.io/tekton: u7c4c11lw-python
  backstage.io/kubernetes-id: u7c4c11lw-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: u7c4c11lw-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
